# Generated by Django 4.2.4 on 2023-10-09 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_waitinglist_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitinglist',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
